"""Add Mistake table

Revision ID: 1b4b6c7ae38a
Revises: d3ede255291a
Create Date: 2025-09-19 11:13:21.166743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4b6c7ae38a'
down_revision = 'd3ede255291a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('mock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_id'], ['mocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mistakes')
    # ### end Alembic commands ###
