"""Add tier column to mocks

Revision ID: 350668a7a608
Revises: 37d33f52c5bb
Create Date: 2025-09-30 18:52:34.815504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350668a7a608'
down_revision = '37d33f52c5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
