"""Add section and type to mistakes

Revision ID: 3634f2be68f8
Revises: 547416f65b56
Create Date: 2025-09-21 02:27:10.496348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3634f2be68f8'
down_revision = '547416f65b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_column('question_type')
        batch_op.drop_column('section_name')

    # ### end Alembic commands ###
