"""Add tier to mock table

Revision ID: 37d33f52c5bb
Revises: a4c27b0637ea
Create Date: 2025-09-30 11:26:09.593241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d33f52c5bb'
down_revision = 'a4c27b0637ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
