"""Add sections table

Revision ID: 547416f65b56
Revises: 9cd0e8340a3a
Create Date: 2025-09-21 00:17:28.618296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547416f65b56'
down_revision = '9cd0e8340a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('unattempted_count', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('mock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_id'], ['mocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    # ### end Alembic commands ###
