"""Add total_marks to Mock model

Revision ID: 5ce85b163d2b
Revises: 350668a7a608
Create Date: 2025-09-30 19:00:18.058002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce85b163d2b'
down_revision = '350668a7a608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_marks', sa.Integer(), server_default='200', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.drop_column('total_marks')

    # ### end Alembic commands ###
