"""Add is_analyzed to Mock model

Revision ID: 79cc9c4f3f84
Revises: 3634f2be68f8 
Create Date: 2025-09-21 20:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cc9c4f3f84'
down_revision = '3634f2be68f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # --- FIX IS HERE: Changed 'mock' to 'mocks' ---
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # --- FIX IS HERE: Changed 'mock' to 'mocks' ---
    with op.batch_alter_table('mocks', schema=None) as batch_op:
        batch_op.drop_column('is_analyzed')
    # ### end Alembic commands ###