"""Add notes to Mistake model

Revision ID: 866a04273e31
Revises: 79cc9c4f3f84
Create Date: 2025-09-22 00:19:19.908042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866a04273e31'
down_revision = '79cc9c4f3f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('section_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('section_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
