"""Update mistake model for full answer text

Revision ID: 9107641bd8a6
Revises: 5ce85b163d2b
Create Date: 2025-10-02 12:31:00.796422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9107641bd8a6'
down_revision = '5ce85b163d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('user_answer', sa.Text(), nullable=True))
    op.add_column('mistakes', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('mistakes', sa.Column('is_recalled', sa.Boolean(), nullable=True))
    op.add_column('mistakes', sa.Column('is_practiced', sa.Boolean(), nullable=True))
    op.add_column('mistakes', sa.Column('last_practiced_date', sa.DateTime(), nullable=True))
    op.drop_column('mistakes', 'correct_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('correct_option', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_column('mistakes', 'last_practiced_date')
    op.drop_column('mistakes', 'is_practiced')
    op.drop_column('mistakes', 'is_recalled')
    op.drop_column('mistakes', 'correct_answer')
    op.drop_column('mistakes', 'user_answer')
    # ### end Alembic commands ###
