"""Add topic to Mistake table

Revision ID: 9cd0e8340a3a
Revises: 1b4b6c7ae38a
Create Date: 2025-09-20 20:01:25.664474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd0e8340a3a'
down_revision = '1b4b6c7ae38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
