"""Add practice mode fields to Mistake model

Revision ID: a4c27b0637ea
Revises: a37ad2e4fb0e
Create Date: 2025-09-28 17:16:52.272250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c27b0637ea'
down_revision = 'a37ad2e4fb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('correct_option', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('correct_option')
        batch_op.drop_column('options')
        batch_op.drop_column('question_text')

    # ### end Alembic commands ###
