"""Initial migration

Revision ID: d3ede255291a
Revises: 
Create Date: 2025-09-19 00:36:20.113633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ede255291a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('score_overall', sa.Float(), nullable=False),
    sa.Column('percentile_overall', sa.Float(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mocks')
    # ### end Alembic commands ###
